<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="187980" started-at="2018-11-17T14:46:49Z" finished-at="2018-11-17T14:49:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="187980" started-at="2018-11-17T14:46:49Z" finished-at="2018-11-17T14:49:57Z">
      <class name="Shein.SheinTestAutomationMaven.Shein">
        <test-method status="PASS" signature="setUp()[pri:0, instance:Shein.SheinTestAutomationMaven.Shein@617c74e5]" name="setUp" is-config="true" duration-ms="9756" started-at="2018-11-17T14:46:39Z" finished-at="2018-11-17T14:46:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="invalidSignUp()[pri:1, instance:Shein.SheinTestAutomationMaven.Shein@617c74e5]" name="invalidSignUp" duration-ms="34435" started-at="2018-11-17T14:46:49Z" finished-at="2018-11-17T14:47:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidSignUp -->
        <test-method status="PASS" signature="invalidSignIn()[pri:2, instance:Shein.SheinTestAutomationMaven.Shein@617c74e5]" name="invalidSignIn" duration-ms="37880" started-at="2018-11-17T14:47:24Z" finished-at="2018-11-17T14:48:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidSignIn -->
        <test-method status="FAIL" signature="sheinHappyScenario()[pri:3, instance:Shein.SheinTestAutomationMaven.Shein@617c74e5]" name="sheinHappyScenario" duration-ms="115566" started-at="2018-11-17T14:48:01Z" finished-at="2018-11-17T14:49:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assert Number of Items in the Bag expected [3] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assert Number of Items in the Bag expected [3] but found [2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at PageObjects.SheinGoods.verifyBag(SheinGoods.java:47)
at Shein.SheinTestAutomationMaven.Shein.sheinHappyScenario(Shein.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sheinHappyScenario -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Shein.SheinTestAutomationMaven.Shein@617c74e5]" name="tearDown" is-config="true" duration-ms="2226" started-at="2018-11-17T14:49:57Z" finished-at="2018-11-17T14:49:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Shein.SheinTestAutomationMaven.Shein -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
